spring:
  application:
    name: sqs-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/productdatabase?searchpath=orders_schema
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    
server:
  port: 8087
  
app:
  config:
    aws:
      region: ap-south-1
      access-key-id: AKIAWON4OXQ7GLTRXJQV
      secret-key-id: 2oFUlSxPOM2tiPuGM4Vrpa/0F+nR72DyybWzqoH/
    message:
      queue:
        topic: sample-queue
springdoc:
  api-docs:
    path: /swagger-ui.html       
        


      
      